### PR TITLE
Fix to avoid the duplicating of topiclist class unnecessarily in the …

### PR DESCRIPTION
**Pull request by Galixte**
…display

Hi @senky,

I suggest you this fix made by tombrraid on my board: http://www.ezcom-fr.com/viewtopic.php?p=4783#p4783.

Regards.

### CODE REVIEW

**Comment by senky** [comment]
@Galixte what is the actual difference?

**Comment by Galixte** [comment]
@senky with your code the topiclist class is used many times each time there is a message to display while with this fix this class is used only once for all messages.

**Comment by senky** [comment]
Oh sure, you are right! Thanks for your PR!

**Comment by Galixte** [comment]
Thanks you too for merging. ;)

**Pull request merged**
